export const API_BASE = '/api'
export const POLL_INTERVAL = 3000
export const PAGE_SIZE = 20
export const VIRTUAL_TABLE_THRESHOLD = 50

export const COLUMN_LABEL_MAP: Record<string, string> = {
  p_value: 'P值',
  statistic: '统计量',
  df: '自由度',
  sum_sq: '平方和',
  mean_sq: '均方',
  f_value: 'F值',
  group: '分组',
  mean: '均值',
  sd: '标准差',
  se: '标准误',
  n: '样本量',
  letter: '显著性字母',
  estimate: '估计值',
  std_error: '标准误差',
  t_value: 't值',
  z_value: 'z值',
  r_squared: 'R²',
  method: '方法',
  term: '项',
  conf_int_low: 'CI下限',
  conf_int_high: 'CI上限',
  chi_squared: 'χ²',
  correlation: '相关系数',
  var1: '变量1',
  var2: '变量2',
  median: '中位数',
  min: '最小值',
  max: '最大值',
  q1: 'Q1',
  q3: 'Q3',
  iqr: 'IQR',
  cv: 'CV%',
  skewness: '偏度',
  kurtosis: '峰度',
  eigenvalue: '特征值',
  proportion: '方差贡献率',
  cumulative: '累计贡献率',
  stress: 'Stress值',
  missing: '缺失值',
  statistic_w: 'W统计量',
  numerator_df: '分子自由度',
  denominator_df: '分母自由度',
  sample_id: '样本ID',
  variable: '变量',
  species: '物种',
  axis: '轴',
  n_x: 'N(x)',
  n_y: 'N(y)',
}
